CHAN_CRAWLER = "4chan_crawler"
COLD_START_CRAWLER="cold_start_crawler"
LOG_FILE_NAME_COLD_START_CRAWLER="cold_start_crawler.log"


# FAKTORY CONFIGURATIONS
FAKTORY_SERVER_URL = "FAKTORY_SERVER_URL"
FAKTORY_CONSUMER_ROLE = "consumer"
FAKTORY_PRODUCER_ROLE = "producer"